### PR TITLE
Support M ISO property

### PR DESCRIPTION
**Pull request by merkys**
This PR implements support for isotopes read from `M ISO` lines. Partially fixes [RT#134837](https://rt.cpan.org/Ticket/Display.html?id=134837).

### CODE REVIEW

**Comment by oalders** [comment]
Hi @merkys!

This repository is meant to be read-only. Normally I would point you towards the authoritative repository for this pull request, but I'm guessing it does not exist on GitHub. I'm guessing the original author is @i-tub?

**Comment by merkys** [comment]
Thanks for prompt response, @oalders! I am aware that @gitpan repositories are read-only. Neverheless, I assumed it is OK to open up PRs here to enable other users of Chemistry::File::MDLMol to use the patched module. Thank you for pinging the original author. I have opened an CPAN RT ticket some time ago, AFAIK RT also pings package maintainers.

**Comment by i-tub** [comment]
Thanks for the ping. Yes, I'm the original author, but I'm sorry to say that I haven't touched these modules for over a decade, and I don't expect to do so in the future. If anyone wants to take them over, I'd be more than happy to give them away! :-)

**Comment by merkys** [comment]
Thank you for prompt reaction, @i-tub! I would happily take over or co-maintain these modules.

**Comment by oalders** [comment]
@merkys, @i-tub should assign the perms to https://metacpan.org/author/MERKYS?

**Comment by merkys** [comment]
> @merkys, @i-tub should assign the perms to https://metacpan.org/author/MERKYS?

@oalders, this is correct.

**Comment by i-tub** [comment]
I've made @merkys co-maintainer for all the Chemistry-* distributions I "own" on pause.cpan.org.

**Comment by merkys** [comment]
Thanks a lot, @i-tub! I would like to have the source of Chemistry-* distributions on GitHub. Would you be OK with that? I can create a GitHub organization for them and make us two members of that organization. Alternatively, I could store them as my personal and make you a collaborator with write access. Which way you prefer?

**Comment by i-tub** [comment]
Of course @merkys , that would be great! Back in the day, I used CVS on SourceForge, but these days I much prefer GitHub. The CVS repos are still around; perhaps it would be good to convert them to have the full history.

I'm OK with either an organization or being a collaborator to your personal repo.

**Comment by merkys** [comment]
> Of course @merkys , that would be great! Back in the day, I used CVS on SourceForge, but these days I much prefer GitHub. The CVS repos are still around; perhaps it would be good to convert them to have the full history.

Great! Am I right that this is the correct link for Chemistry-* CVS on SourceForge: http://perlmol.cvs.sourceforge.net? I managed to access one of the modules with CVS, so I assume I will be able to get them all. I will look into converting CVS to git - I saw [some tools doing that](https://docs.gitlab.com/ee/user/project/import/cvs.html#how-to-migrate), will try.

> I'm OK with either an organization or being a collaborator to your personal repo.

Since there are many modules, I think a separate organization would be a better way. Would it be OK to name it 'perlmol'?

**Comment by i-tub** [comment]
That link is correct. A `perlmol` organization sounds good to me, thanks!

I'm not an expert on converting repos, but SourceForge also has some tips here: https://sourceforge.net/p/forge/documentation/CVS/ I tried getting everything from  rsync://a.cvs.sourceforge.net/cvsroot/perlmol/ and converted one of the repos (chemistry-mol) with `git cvsimport` and it seems to work fine despite being the less favored choice. Maybe these repos are easy (pretty much a linear history, IIRC).

**Comment by merkys** [comment]
I have converted CVS repositories with `git cvsimport` and imported them into new GitHub organization @perlmol (you should have received my invitation). Currently I am finalizing some repository details, should not take long.

Two repositories were locked in CVS level, thus I was unable to retrieve them:
* chemistry-file-sln
* chemistry-file-vrml

Maybe you can unlock them so that I can import these too?

**Comment by i-tub** [comment]
I just joined the organization, thanks! Regarding the locks, I suggest removing the directories named `#cvs.lock` from your local copy of the CVS repos and trying again. I don't think there's anything I can do to unlock the repos as held by SourceForge, because as far as I understand, when they deprecated CVS years ago they made all CVS repos read-only.

**Comment by merkys** [comment]
The problem is that I cannot even create a local copy as modules seem to be locked on the server:
```
$ cvs -z3 -d:pserver:anonymous@a.cvs.sourceforge.net:/cvsroot/perlmol co -P chemistry-file-sln
cvs checkout: Updating chemistry-file-sln
cvs checkout: [11:48:44] waiting for anoncvs_perlmol's lock in /cvsroot/perlmol/chemistry-file-sln
```
And this goes on and on. I have tried using `cvs release`, but that does not improve the situation:
```
$ cvs -z3 -d:pserver:anoncvs_perlmol@a.cvs.sourceforge.net:/cvsroot/perlmol release chemistry-file-sln
U Changes
U MANIFEST
U MANIFEST.SKIP
U Makefile.PL
U Parser.yp
U README
U TODO
You have [0] altered files in this repository.
Are you sure you want to release directory `chemistry-file-sln': y
```
Maybe this is because the repos in SourceForge are read-only. In the worst case I can push these two modules without their history.

**Comment by i-tub** [comment]
I just created the last two repos. The trick was using rsync instead of cvs to download them from SourceForge, and then remove the locks manually from the local copies.

**Comment by merkys** [comment]
Great, thank you very much! Is is OK if I close this PR (will commit into new repositories instead) and we continue our cooperation via email, Perl RT and GitHub PRs?

**Comment by i-tub** [comment]
Sounds good to me!

**Pull request closed without merging**
